name: Android Fastlane Firebase App Distribution Workflow

on:
  push:
    branches:
      - development

jobs:
  ditribute_to_firebase_app_distribution:
    name: Distribute to Firebase App Distribution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' 

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true
          working-directory: ./android

      - name: Install Fastlane
        run: gem install fastlane

      - name: Build and Distribute to Firebase App Distribution
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: |
          bundle exec fastlane android firebase_distribution
          working-directory: ./android